### ISSUE TITLE
Idea?

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceTB/OSTB_Series4_OpenCyclams#1]
I was wondering if this would be worth making as a way to see how simplified we can make these compounds? 

![N%u2010benzyl%u2010N%u2010 6%u2010(N%u2010 benzylpropanamido)hexyl propanamide](https://user-images.githubusercontent.com/3164942/120864539-5e044a00-c55a-11eb-9d15-9b8cef5c1b13.png)

![dibenzyl 6-(dibenzylamino)hexyl amine](https://user-images.githubusercontent.com/3164942/120864725-a91e5d00-c55a-11eb-9ec8-aa4bfa63469f.png)

![N%u2010benzyl%u2010N%u2010 6%u2010(ethylamino)hexyl propanamide](https://user-images.githubusercontent.com/3164942/120874503-ef80b580-c574-11eb-82a9-99d7d4047cf5.png)

**Comment by MFernflower** [comment]
@mattodd @KlementineJBS

**Comment by KlementineJBS** [comment]
As regards the simple benzene pendant group, [this paper](https://pubs.acs.org/doi/abs/10.1021/acs.jmedchem.7b01569) found that activity was better with larger + more hydrophobic groups. Certainly could be interesting to try the middle compound to see the effect of doubling the pendant groups, though!

**Comment by MFernflower** [comment]
Do we know if the triazole ring is needed?

I don't have access to the papers @mattodd

**Comment by MFernflower** [comment]
@KlementineJBS

Would it be possible for you post an update of what compounds you are
making / plan to make

**Comment by mattodd** [comment]
Yes, I think the take home here is that we could use a summary of the SAR in the wiki section, to learn perhaps what is likely to be the most productive designs to pursue. Am assuming that that's on the cards @KlementineJBS 
Access to papers @MFernflower is a perpetual problem, though. I had thought that the embargo period for this paper would have passed and it's now public domain? Is there an accepted version that is publicly available on a Sydney uni repository @KlementineJBS ? I realise I ought to know this.

**Comment by MFernflower** [comment]
@mattodd I was able to read the preprint - It did take a bit of digging to find however
